// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/xrpl/rpc/v1/get_ledger_diff.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "org/xrpl/rpc/v1/ledger.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto;
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
class GetLedgerDiffRequest;
class GetLedgerDiffRequestDefaultTypeInternal;
extern GetLedgerDiffRequestDefaultTypeInternal _GetLedgerDiffRequest_default_instance_;
class GetLedgerDiffResponse;
class GetLedgerDiffResponseDefaultTypeInternal;
extern GetLedgerDiffResponseDefaultTypeInternal _GetLedgerDiffResponse_default_instance_;
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::xrpl::rpc::v1::GetLedgerDiffRequest* Arena::CreateMaybeMessage<::org::xrpl::rpc::v1::GetLedgerDiffRequest>(Arena*);
template<> ::org::xrpl::rpc::v1::GetLedgerDiffResponse* Arena::CreateMaybeMessage<::org::xrpl::rpc::v1::GetLedgerDiffResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {

// ===================================================================

class GetLedgerDiffRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.GetLedgerDiffRequest) */ {
 public:
  GetLedgerDiffRequest();
  virtual ~GetLedgerDiffRequest();

  GetLedgerDiffRequest(const GetLedgerDiffRequest& from);
  GetLedgerDiffRequest(GetLedgerDiffRequest&& from) noexcept
    : GetLedgerDiffRequest() {
    *this = ::std::move(from);
  }

  inline GetLedgerDiffRequest& operator=(const GetLedgerDiffRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetLedgerDiffRequest& operator=(GetLedgerDiffRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetLedgerDiffRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetLedgerDiffRequest* internal_default_instance() {
    return reinterpret_cast<const GetLedgerDiffRequest*>(
               &_GetLedgerDiffRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GetLedgerDiffRequest* other);
  friend void swap(GetLedgerDiffRequest& a, GetLedgerDiffRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetLedgerDiffRequest* New() const final {
    return CreateMaybeMessage<GetLedgerDiffRequest>(nullptr);
  }

  GetLedgerDiffRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetLedgerDiffRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetLedgerDiffRequest& from);
  void MergeFrom(const GetLedgerDiffRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetLedgerDiffRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.xrpl.rpc.v1.GetLedgerDiffRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto);
    return ::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string client_ip = 4;
  void clear_client_ip();
  static const int kClientIpFieldNumber = 4;
  const std::string& client_ip() const;
  void set_client_ip(const std::string& value);
  void set_client_ip(std::string&& value);
  void set_client_ip(const char* value);
  void set_client_ip(const char* value, size_t size);
  std::string* mutable_client_ip();
  std::string* release_client_ip();
  void set_allocated_client_ip(std::string* client_ip);

  // .org.xrpl.rpc.v1.LedgerSpecifier base_ledger = 1;
  bool has_base_ledger() const;
  void clear_base_ledger();
  static const int kBaseLedgerFieldNumber = 1;
  const ::org::xrpl::rpc::v1::LedgerSpecifier& base_ledger() const;
  ::org::xrpl::rpc::v1::LedgerSpecifier* release_base_ledger();
  ::org::xrpl::rpc::v1::LedgerSpecifier* mutable_base_ledger();
  void set_allocated_base_ledger(::org::xrpl::rpc::v1::LedgerSpecifier* base_ledger);

  // .org.xrpl.rpc.v1.LedgerSpecifier desired_ledger = 2;
  bool has_desired_ledger() const;
  void clear_desired_ledger();
  static const int kDesiredLedgerFieldNumber = 2;
  const ::org::xrpl::rpc::v1::LedgerSpecifier& desired_ledger() const;
  ::org::xrpl::rpc::v1::LedgerSpecifier* release_desired_ledger();
  ::org::xrpl::rpc::v1::LedgerSpecifier* mutable_desired_ledger();
  void set_allocated_desired_ledger(::org::xrpl::rpc::v1::LedgerSpecifier* desired_ledger);

  // bool include_blobs = 3;
  void clear_include_blobs();
  static const int kIncludeBlobsFieldNumber = 3;
  bool include_blobs() const;
  void set_include_blobs(bool value);

  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.GetLedgerDiffRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_ip_;
  ::org::xrpl::rpc::v1::LedgerSpecifier* base_ledger_;
  ::org::xrpl::rpc::v1::LedgerSpecifier* desired_ledger_;
  bool include_blobs_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto;
};
// -------------------------------------------------------------------

class GetLedgerDiffResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.GetLedgerDiffResponse) */ {
 public:
  GetLedgerDiffResponse();
  virtual ~GetLedgerDiffResponse();

  GetLedgerDiffResponse(const GetLedgerDiffResponse& from);
  GetLedgerDiffResponse(GetLedgerDiffResponse&& from) noexcept
    : GetLedgerDiffResponse() {
    *this = ::std::move(from);
  }

  inline GetLedgerDiffResponse& operator=(const GetLedgerDiffResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetLedgerDiffResponse& operator=(GetLedgerDiffResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetLedgerDiffResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetLedgerDiffResponse* internal_default_instance() {
    return reinterpret_cast<const GetLedgerDiffResponse*>(
               &_GetLedgerDiffResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GetLedgerDiffResponse* other);
  friend void swap(GetLedgerDiffResponse& a, GetLedgerDiffResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetLedgerDiffResponse* New() const final {
    return CreateMaybeMessage<GetLedgerDiffResponse>(nullptr);
  }

  GetLedgerDiffResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetLedgerDiffResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetLedgerDiffResponse& from);
  void MergeFrom(const GetLedgerDiffResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetLedgerDiffResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.xrpl.rpc.v1.GetLedgerDiffResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto);
    return ::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .org.xrpl.rpc.v1.RawLedgerObjects ledger_objects = 1;
  bool has_ledger_objects() const;
  void clear_ledger_objects();
  static const int kLedgerObjectsFieldNumber = 1;
  const ::org::xrpl::rpc::v1::RawLedgerObjects& ledger_objects() const;
  ::org::xrpl::rpc::v1::RawLedgerObjects* release_ledger_objects();
  ::org::xrpl::rpc::v1::RawLedgerObjects* mutable_ledger_objects();
  void set_allocated_ledger_objects(::org::xrpl::rpc::v1::RawLedgerObjects* ledger_objects);

  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.GetLedgerDiffResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::org::xrpl::rpc::v1::RawLedgerObjects* ledger_objects_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetLedgerDiffRequest

// .org.xrpl.rpc.v1.LedgerSpecifier base_ledger = 1;
inline bool GetLedgerDiffRequest::has_base_ledger() const {
  return this != internal_default_instance() && base_ledger_ != nullptr;
}
inline const ::org::xrpl::rpc::v1::LedgerSpecifier& GetLedgerDiffRequest::base_ledger() const {
  const ::org::xrpl::rpc::v1::LedgerSpecifier* p = base_ledger_;
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.GetLedgerDiffRequest.base_ledger)
  return p != nullptr ? *p : *reinterpret_cast<const ::org::xrpl::rpc::v1::LedgerSpecifier*>(
      &::org::xrpl::rpc::v1::_LedgerSpecifier_default_instance_);
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier* GetLedgerDiffRequest::release_base_ledger() {
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.GetLedgerDiffRequest.base_ledger)
  
  ::org::xrpl::rpc::v1::LedgerSpecifier* temp = base_ledger_;
  base_ledger_ = nullptr;
  return temp;
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier* GetLedgerDiffRequest::mutable_base_ledger() {
  
  if (base_ledger_ == nullptr) {
    auto* p = CreateMaybeMessage<::org::xrpl::rpc::v1::LedgerSpecifier>(GetArenaNoVirtual());
    base_ledger_ = p;
  }
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.GetLedgerDiffRequest.base_ledger)
  return base_ledger_;
}
inline void GetLedgerDiffRequest::set_allocated_base_ledger(::org::xrpl::rpc::v1::LedgerSpecifier* base_ledger) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_ledger_);
  }
  if (base_ledger) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      base_ledger = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base_ledger, submessage_arena);
    }
    
  } else {
    
  }
  base_ledger_ = base_ledger;
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.GetLedgerDiffRequest.base_ledger)
}

// .org.xrpl.rpc.v1.LedgerSpecifier desired_ledger = 2;
inline bool GetLedgerDiffRequest::has_desired_ledger() const {
  return this != internal_default_instance() && desired_ledger_ != nullptr;
}
inline const ::org::xrpl::rpc::v1::LedgerSpecifier& GetLedgerDiffRequest::desired_ledger() const {
  const ::org::xrpl::rpc::v1::LedgerSpecifier* p = desired_ledger_;
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.GetLedgerDiffRequest.desired_ledger)
  return p != nullptr ? *p : *reinterpret_cast<const ::org::xrpl::rpc::v1::LedgerSpecifier*>(
      &::org::xrpl::rpc::v1::_LedgerSpecifier_default_instance_);
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier* GetLedgerDiffRequest::release_desired_ledger() {
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.GetLedgerDiffRequest.desired_ledger)
  
  ::org::xrpl::rpc::v1::LedgerSpecifier* temp = desired_ledger_;
  desired_ledger_ = nullptr;
  return temp;
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier* GetLedgerDiffRequest::mutable_desired_ledger() {
  
  if (desired_ledger_ == nullptr) {
    auto* p = CreateMaybeMessage<::org::xrpl::rpc::v1::LedgerSpecifier>(GetArenaNoVirtual());
    desired_ledger_ = p;
  }
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.GetLedgerDiffRequest.desired_ledger)
  return desired_ledger_;
}
inline void GetLedgerDiffRequest::set_allocated_desired_ledger(::org::xrpl::rpc::v1::LedgerSpecifier* desired_ledger) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(desired_ledger_);
  }
  if (desired_ledger) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      desired_ledger = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, desired_ledger, submessage_arena);
    }
    
  } else {
    
  }
  desired_ledger_ = desired_ledger;
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.GetLedgerDiffRequest.desired_ledger)
}

// bool include_blobs = 3;
inline void GetLedgerDiffRequest::clear_include_blobs() {
  include_blobs_ = false;
}
inline bool GetLedgerDiffRequest::include_blobs() const {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.GetLedgerDiffRequest.include_blobs)
  return include_blobs_;
}
inline void GetLedgerDiffRequest::set_include_blobs(bool value) {
  
  include_blobs_ = value;
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.GetLedgerDiffRequest.include_blobs)
}

// string client_ip = 4;
inline void GetLedgerDiffRequest::clear_client_ip() {
  client_ip_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& GetLedgerDiffRequest::client_ip() const {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
  return client_ip_.GetNoArena();
}
inline void GetLedgerDiffRequest::set_client_ip(const std::string& value) {
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
}
inline void GetLedgerDiffRequest::set_client_ip(std::string&& value) {
  
  client_ip_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
}
inline void GetLedgerDiffRequest::set_client_ip(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
}
inline void GetLedgerDiffRequest::set_client_ip(const char* value, size_t size) {
  
  client_ip_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
}
inline std::string* GetLedgerDiffRequest::mutable_client_ip() {
  
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
  return client_ip_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* GetLedgerDiffRequest::release_client_ip() {
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
  
  return client_ip_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void GetLedgerDiffRequest::set_allocated_client_ip(std::string* client_ip) {
  if (client_ip != nullptr) {
    
  } else {
    
  }
  client_ip_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), client_ip);
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.GetLedgerDiffRequest.client_ip)
}

// -------------------------------------------------------------------

// GetLedgerDiffResponse

// .org.xrpl.rpc.v1.RawLedgerObjects ledger_objects = 1;
inline bool GetLedgerDiffResponse::has_ledger_objects() const {
  return this != internal_default_instance() && ledger_objects_ != nullptr;
}
inline const ::org::xrpl::rpc::v1::RawLedgerObjects& GetLedgerDiffResponse::ledger_objects() const {
  const ::org::xrpl::rpc::v1::RawLedgerObjects* p = ledger_objects_;
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.GetLedgerDiffResponse.ledger_objects)
  return p != nullptr ? *p : *reinterpret_cast<const ::org::xrpl::rpc::v1::RawLedgerObjects*>(
      &::org::xrpl::rpc::v1::_RawLedgerObjects_default_instance_);
}
inline ::org::xrpl::rpc::v1::RawLedgerObjects* GetLedgerDiffResponse::release_ledger_objects() {
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.GetLedgerDiffResponse.ledger_objects)
  
  ::org::xrpl::rpc::v1::RawLedgerObjects* temp = ledger_objects_;
  ledger_objects_ = nullptr;
  return temp;
}
inline ::org::xrpl::rpc::v1::RawLedgerObjects* GetLedgerDiffResponse::mutable_ledger_objects() {
  
  if (ledger_objects_ == nullptr) {
    auto* p = CreateMaybeMessage<::org::xrpl::rpc::v1::RawLedgerObjects>(GetArenaNoVirtual());
    ledger_objects_ = p;
  }
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.GetLedgerDiffResponse.ledger_objects)
  return ledger_objects_;
}
inline void GetLedgerDiffResponse::set_allocated_ledger_objects(::org::xrpl::rpc::v1::RawLedgerObjects* ledger_objects) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(ledger_objects_);
  }
  if (ledger_objects) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ledger_objects = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ledger_objects, submessage_arena);
    }
    
  } else {
    
  }
  ledger_objects_ = ledger_objects;
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.GetLedgerDiffResponse.ledger_objects)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto
