// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/xrpl/rpc/v1/xrp_ledger.proto

#include "org/xrpl/rpc/v1/xrp_ledger.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto[] =
  "\n org/xrpl/rpc/v1/xrp_ledger.proto\022\017org."
  "xrpl.rpc.v1\032&org/xrpl/rpc/v1/get_account"
  "_info.proto\032\035org/xrpl/rpc/v1/get_fee.pro"
  "to\032\034org/xrpl/rpc/v1/submit.proto\032%org/xr"
  "pl/rpc/v1/get_transaction.proto\0325org/xrp"
  "l/rpc/v1/get_account_transaction_history"
  ".proto\032 org/xrpl/rpc/v1/get_ledger.proto"
  "\032&org/xrpl/rpc/v1/get_ledger_entry.proto"
  "\032%org/xrpl/rpc/v1/get_ledger_data.proto\032"
  "%org/xrpl/rpc/v1/get_ledger_diff.proto2\227"
  "\007\n\023XRPLedgerAPIService\022a\n\016GetAccountInfo"
  "\022&.org.xrpl.rpc.v1.GetAccountInfoRequest"
  "\032\'.org.xrpl.rpc.v1.GetAccountInfoRespons"
  "e\022I\n\006GetFee\022\036.org.xrpl.rpc.v1.GetFeeRequ"
  "est\032\037.org.xrpl.rpc.v1.GetFeeResponse\022j\n\021"
  "SubmitTransaction\022).org.xrpl.rpc.v1.Subm"
  "itTransactionRequest\032*.org.xrpl.rpc.v1.S"
  "ubmitTransactionResponse\022a\n\016GetTransacti"
  "on\022&.org.xrpl.rpc.v1.GetTransactionReque"
  "st\032\'.org.xrpl.rpc.v1.GetTransactionRespo"
  "nse\022\213\001\n\034GetAccountTransactionHistory\0224.o"
  "rg.xrpl.rpc.v1.GetAccountTransactionHist"
  "oryRequest\0325.org.xrpl.rpc.v1.GetAccountT"
  "ransactionHistoryResponse\022R\n\tGetLedger\022!"
  ".org.xrpl.rpc.v1.GetLedgerRequest\032\".org."
  "xrpl.rpc.v1.GetLedgerResponse\022a\n\016GetLedg"
  "erEntry\022&.org.xrpl.rpc.v1.GetLedgerEntry"
  "Request\032\'.org.xrpl.rpc.v1.GetLedgerEntry"
  "Response\022^\n\rGetLedgerData\022%.org.xrpl.rpc"
  ".v1.GetLedgerDataRequest\032&.org.xrpl.rpc."
  "v1.GetLedgerDataResponse\022^\n\rGetLedgerDif"
  "f\022%.org.xrpl.rpc.v1.GetLedgerDiffRequest"
  "\032&.org.xrpl.rpc.v1.GetLedgerDiffResponse"
  "B\023\n\017org.xrpl.rpc.v1P\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_deps[9] = {
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5faccount_5finfo_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5faccount_5ftransaction_5fhistory_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5ffee_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdata_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fdiff_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5ftransaction_2eproto,
  &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fsubmit_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_once;
static bool descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto = {
  &descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_initialized, descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto, "org/xrpl/rpc/v1/xrp_ledger.proto", 1349,
  &descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_once, descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_sccs, descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto_deps, 0, 9,
  schemas, file_default_instances, TableStruct_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto::offsets,
  file_level_metadata_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto, 0, file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto, file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_org_2fxrpl_2frpc_2fv1_2fxrp_5fledger_2eproto), true);
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
